# Generated by Django 5.1.4 on 2025-12-30 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('name', models.CharField(help_text="Department name (e.g., 'Anatomy', 'Medicine', 'Surgery')", max_length=128, unique=True)),
                ('code', models.CharField(blank=True, help_text="Department code (e.g., 'ANAT', 'MED')", max_length=32, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('name', models.CharField(help_text='Program name (e.g., MBBS, BDS, MD, etc.)', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Program description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this program is currently active')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('period_type', models.CharField(choices=[('YEAR', 'Year'), ('BLOCK', 'Block'), ('MODULE', 'Module')], help_text='Type of academic period', max_length=16)),
                ('name', models.CharField(help_text="Period name (e.g., 'Year 1', 'Block 1', 'Module A')", max_length=128)),
                ('start_date', models.DateField(blank=True, help_text='Period start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Period end date', null=True)),
                ('parent_period', models.ForeignKey(blank=True, help_text='Parent period for hierarchical structure (YEAR -> BLOCK -> MODULE)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_periods', to='academics.academicperiod')),
            ],
            options={
                'ordering': ['period_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('name', models.CharField(help_text="Batch name (e.g., '2024 Batch', 'Fall 2024')", max_length=128)),
                ('start_year', models.PositiveSmallIntegerField(help_text='Batch start year')),
                ('program', models.ForeignKey(help_text='Program this batch belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academics.program')),
            ],
            options={
                'ordering': ['program', 'start_year'],
                'unique_together': {('program', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('name', models.CharField(help_text="Group name (e.g., 'Group A', 'Section 1')", max_length=128)),
                ('batch', models.ForeignKey(help_text='Batch this group belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.batch')),
            ],
            options={
                'ordering': ['batch', 'name'],
                'unique_together': {('batch', 'name')},
            },
        ),
    ]
