# Generated by Django 5.1.4 on 2026-01-02 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('code', models.CharField(help_text="Course code (e.g., 'ANAT-101', 'PHYS-201')", max_length=32, unique=True)),
                ('name', models.CharField(help_text="Course name (e.g., 'Human Anatomy', 'Physiology')", max_length=255)),
                ('credits', models.PositiveSmallIntegerField(default=3, help_text='Credit hours for this course')),
                ('academic_period', models.ForeignKey(blank=True, help_text='Academic period this course belongs to (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.academicperiod')),
                ('department', models.ForeignKey(help_text='Department offering this course', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.department')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('name', models.CharField(help_text="Section name (e.g., 'Section A', 'Morning Batch')", max_length=128)),
                ('capacity', models.PositiveSmallIntegerField(default=50, help_text='Maximum number of students')),
                ('academic_period', models.ForeignKey(help_text='Academic period this section belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.academicperiod')),
                ('course', models.ForeignKey(help_text='Course this section belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.course')),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty assigned to this section (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_sections', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Group this section is assigned to (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.group')),
            ],
            options={
                'ordering': ['course', 'name'],
                'unique_together': {('course', 'academic_period', 'name')},
            },
        ),
    ]
