# Generated by custom migration for teacher ForeignKey conversion

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_teacher_data(apps, schema_editor):
    """
    Copy teacher CharField data to teacher_name field.
    Safely handles the case where _teacher_old field exists.
    """
    Section = apps.get_model("academics", "Section")

    # Iterate through all sections and copy teacher data
    for section in Section.objects.all():
        # The field will be named _teacher_old at this point in the migration
        # Check for existence and copy even empty strings
        if hasattr(section, '_teacher_old'):
            section.teacher_name = section._teacher_old or ""
            section.save(update_fields=["teacher_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_term"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Remove old unique_together constraint first
        migrations.AlterUniqueTogether(
            name="section",
            unique_together=set(),
        ),
        # Step 2: Rename teacher (CharField) to _teacher_old temporarily
        migrations.RenameField(
            model_name="section",
            old_name="teacher",
            new_name="_teacher_old",
        ),
        # Step 3: Add new teacher_name CharField
        migrations.AddField(
            model_name="section",
            name="teacher_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display name for teacher (auto-populated from user)",
                max_length=128,
            ),
            preserve_default=False,
        ),
        # Step 4: Copy data from _teacher_old to teacher_name
        migrations.RunPython(
            migrate_teacher_data,
            reverse_code=migrations.RunPython.noop
        ),
        # Step 5: Add new teacher ForeignKey field
        migrations.AddField(
            model_name="section",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Faculty user assigned to teach this section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Step 6: Remove the old _teacher_old CharField
        migrations.RemoveField(
            model_name="section",
            name="_teacher_old",
        ),
        # Step 7: Add new unique_together with ForeignKey teacher
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("course", "term", "teacher")},
        ),
    ]
