# Generated by Django 5.1.4 on 2026-01-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_add_academicperiod_status_fields"),
        ("academics", "0005_add_period_track_block_module"),
    ]

    operations = []
