# Generated by Django 5.1.4 on 2026-01-10 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_merge_20260110_0642"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("finalize_program", "Can finalize program structure"),
                    ("manage_structure", "Can manage program structure"),
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="module",
            name="academics_module_block_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="module",
            name="academics_module_block_order_unique",
        ),
        migrations.RemoveConstraint(
            model_name="period",
            name="academics_period_program_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="period",
            name="academics_period_program_order_unique",
        ),
        migrations.RemoveConstraint(
            model_name="track",
            name="academics_track_program_name_unique",
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent department for hierarchical structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="academics.department",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Department code (e.g., 'ANAT', 'MED')",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                help_text="Department name (e.g., 'Anatomy', 'Medicine', 'Surgery')",
                max_length=128,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "parent")},
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together={("block", "name"), ("block", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="period",
            unique_together={("program", "name"), ("program", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="track",
            unique_together={("program", "name")},
        ),
    ]
