# Generated by Django 5.1.4 on 2026-01-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="address",
            new_name="people_addr_person__61177a_idx",
            old_name="people_address_person_3c4d5e_idx",
        ),
        migrations.RenameIndex(
            model_name="contactinfo",
            new_name="people_cont_person__aee124_idx",
            old_name="people_contact_person_9a7b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="contactinfo",
            new_name="people_cont_type_832e6e_idx",
            old_name="people_contact_type_va_7d8e9f_idx",
        ),
        migrations.RenameIndex(
            model_name="identitydocument",
            new_name="people_iden_person__0dd7df_idx",
            old_name="people_identity_person_6f7g8h_idx",
        ),
        migrations.RenameIndex(
            model_name="identitydocument",
            new_name="people_iden_documen_9dc4da_idx",
            old_name="people_identity_documen_9i0j1k_idx",
        ),
        migrations.RenameIndex(
            model_name="person",
            new_name="people_pers_last_na_c63c6e_idx",
            old_name="people_person_last_na_2b8c1d_idx",
        ),
        migrations.RenameIndex(
            model_name="person",
            new_name="people_pers_nationa_3062c0_idx",
            old_name="people_person_nationa_8f3e4a_idx",
        ),
    ]
