# Generated by Django 5.1.4 on 2026-01-27 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0009_alter_batch_start_year"),
        ("students", "0006_importjob_auto_create"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("FILE", "File"), ("LINK", "Link")], max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="learning/"),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_learning_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningMaterialAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_material_audiences",
                        to="academics.batch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_material_audiences",
                        to="academics.course",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiences",
                        to="learning.learningmaterial",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_material_audiences",
                        to="academics.program",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_material_audiences",
                        to="academics.section",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_material_audiences",
                        to="academics.academicperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningMaterialReadReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_receipts",
                        to="learning.learningmaterial",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_read_receipts",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="learningmaterial",
            index=models.Index(fields=["status"], name="learning_le_status_ba5a44_idx"),
        ),
        migrations.AddIndex(
            model_name="learningmaterial",
            index=models.Index(
                fields=["published_at"], name="learning_le_publish_56e22d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningmaterial",
            index=models.Index(
                fields=["available_from", "available_until"],
                name="learning_le_availab_3211b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="learningmaterialaudience",
            index=models.Index(
                fields=["material", "program"], name="learning_le_materia_b31f88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningmaterialaudience",
            index=models.Index(
                fields=["material", "batch"], name="learning_le_materia_1291cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningmaterialaudience",
            index=models.Index(
                fields=["material", "term"], name="learning_le_materia_c01aef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningmaterialaudience",
            index=models.Index(
                fields=["material", "course"], name="learning_le_materia_26467d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningmaterialaudience",
            index=models.Index(
                fields=["material", "section"], name="learning_le_materia_cb5d01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningmaterialreadreceipt",
            index=models.Index(
                fields=["student", "seen_at"], name="learning_le_student_4b0ce8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="learningmaterialreadreceipt",
            constraint=models.UniqueConstraint(
                fields=("material", "student"), name="uniq_learning_read_receipt"
            ),
        ),
    ]
