import { defineConfig, devices } from '@playwright/test';
import { fileURLToPath } from 'url';
import * as path from 'path';

/**
 * FMU SIMS Playwright Configuration
 *
 * Projects:
 *   setup      — global auth state generation (runs before all tests)
 *   smoke      — @smoke tagged tests, fast CI gate
 *   auth       — auth/session flow tests (no storageState, tests actual login)
 *   admin      — admin role tests (uses saved admin storageState)
 *   registrar  — registrar role tests
 *   faculty    — faculty role tests
 *   student    — student role tests
 *   examcell   — exam cell role tests
 *   public     — unauthenticated public route tests
 *   rbac       — RBAC negative + workflow state machine tests
 *   full       — all of the above (alias used for nightly)
 *
 * Environment variables:
 *   BASE_URL          — Frontend URL (default: http://localhost:5173)
 *   API_BASE_URL      — Backend API URL (default: http://localhost:8010)
 *   PLAYWRIGHT_BASE_URL — Alternative frontend URL (overrides default)
 *
 * See https://playwright.dev/docs/test-configuration
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const BASE_URL =
  process.env.BASE_URL ||
  process.env.PLAYWRIGHT_BASE_URL ||
  'http://localhost:5173';

/** Auth state files generated by global.setup.ts */
const AUTH = {
  admin: path.join(__dirname, 'e2e/auth/.auth/admin.json'),
  registrar: path.join(__dirname, 'e2e/auth/.auth/registrar.json'),
  faculty: path.join(__dirname, 'e2e/auth/.auth/faculty.json'),
  student: path.join(__dirname, 'e2e/auth/.auth/student.json'),
  examcell: path.join(__dirname, 'e2e/auth/.auth/examcell.json'),
};

export default defineConfig({
  testDir: './e2e',

  /* Parallel execution - disabled on CI to reduce flakiness */
  fullyParallel: !process.env.CI,

  /* Fail the build on CI if test.only was accidentally left in source */
  forbidOnly: !!process.env.CI,

  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,

  /* Reduce workers on CI */
  workers: process.env.CI ? 2 : undefined,

  /* Global test timeout */
  timeout: 30000,

  /* Assertion timeout */
  expect: {
    timeout: 8000,
  },

  /* Reporters */
  reporter: [
    ['html', { open: 'never', outputFolder: 'playwright-report' }],
    ['json', { outputFile: 'e2e-results.json' }],
    process.env.CI ? ['github'] : ['list'],
  ],

  /* Shared settings for all projects */
  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    /* Increase navigation timeout for SPA */
    navigationTimeout: 15000,
    actionTimeout: 10000,
  },

  /* Global setup: generates auth storage states */
  globalSetup: './e2e/global.setup.ts',

  /* Test output directory */
  outputDir: 'test-results',

  projects: [
    // ------------------------------------------------------------------
    // SMOKE — minimal fast checks, runs on every PR
    // ------------------------------------------------------------------
    {
      name: 'smoke',
      testMatch: '**/tests/smoke/**/*.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
      },
    },

    // ------------------------------------------------------------------
    // AUTH — tests the actual login/logout/session flows (no storageState)
    // ------------------------------------------------------------------
    {
      name: 'auth',
      testMatch: '**/tests/auth/**/*.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
      },
    },

    // ------------------------------------------------------------------
    // PUBLIC — no auth required
    // ------------------------------------------------------------------
    {
      name: 'public',
      testMatch: '**/tests/public/**/*.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
      },
    },

    // ------------------------------------------------------------------
    // ROLE-BASED — use saved auth states for speed
    // ------------------------------------------------------------------
    {
      name: 'admin',
      testMatch: '**/tests/admin/**/*.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
        storageState: AUTH.admin,
      },
    },

    {
      name: 'registrar',
      testMatch: '**/tests/registrar/**/*.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
        storageState: AUTH.registrar,
      },
    },

    {
      name: 'faculty',
      testMatch: '**/tests/faculty/**/*.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
        storageState: AUTH.faculty,
      },
    },

    {
      name: 'student',
      testMatch: '**/tests/student/**/*.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
        storageState: AUTH.student,
      },
    },

    {
      name: 'examcell',
      testMatch: '**/tests/examcell/**/*.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
        storageState: AUTH.examcell,
      },
    },

    // ------------------------------------------------------------------
    // RBAC — uses multiple role contexts (handled in fixtures)
    // ------------------------------------------------------------------
    {
      name: 'rbac',
      testMatch: '**/tests/rbac/**/*.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
      },
    },

    // ------------------------------------------------------------------
    // FULL — all tests (alias for nightly/on-demand)
    // ------------------------------------------------------------------
    {
      name: 'full',
      testMatch: '**/tests/**/*.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: BASE_URL,
      },
    },
  ],
});
