[pytest]
DJANGO_SETTINGS_MODULE = sims_backend.test_settings
python_files = test_*.py *_test.py tests.py
testpaths = tests sims_backend core
addopts =
    --import-mode=importlib
    --cov
    --cov-report=html
    --cov-report=json:coverage.json
    --cov-report=xml:coverage.xml
    --cov-report=term-missing
    --strict-markers
    --tb=short
    -q
