# Generated by Django 5.1.4 on 2026-01-10 06:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0007_alter_program_options_and_more"),
        ("students", "0005_leaveperiod_student_actual_graduation_year_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique fee type code (e.g., TUITION, EXAM, LIBRARY)",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human readable fee type name", max_length=128
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this fee type can be used"
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="finance_fee_is_acti_c3891d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                ("rule_key", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "threshold_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "fee_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional scope to a specific fee type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies",
                        to="finance.feetype",
                    ),
                ),
            ],
            options={
                "ordering": ["rule_key"],
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                (
                    "voucher_no",
                    models.CharField(
                        help_text="Readable voucher number", max_length=64, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="generated",
                        max_length=32,
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot total for printing (truth derived from ledger)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(
                                Decimal("9999999999.99")
                            ),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student this voucher belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        help_text="Term for which the voucher is issued",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="academics.academicperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "voucher_no"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                ("receipt_no", models.CharField(max_length=64, unique=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online", "Online"),
                            ("scholarship", "Scholarship"),
                            ("waiver", "Waiver"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reference_no", models.CharField(blank=True, max_length=128)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="academics.academicperiod",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="finance.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=8
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="PKR", max_length=8)),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("voucher", "Voucher"),
                            ("payment", "Payment"),
                            ("adjustment", "Adjustment"),
                            ("waiver", "Waiver"),
                            ("scholarship", "Scholarship"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reference_id", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student the entry belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        help_text="Term/academic period for the entry",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="academics.academicperiod",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="finance.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoucherItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Optional metadata for integrations",
                        null=True,
                    ),
                ),
                (
                    "fee_type",
                    models.ForeignKey(
                        help_text="Fee type for this line",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voucher_items",
                        to="finance.feetype",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        help_text="Voucher this line item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ["voucher", "fee_type"],
            },
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("waiver", "Waiver"),
                            ("scholarship", "Scholarship"),
                            ("adjustment", "Adjustment"),
                            ("fine_reversal", "Fine Reversal"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("reason", models.TextField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="academics.academicperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "term", "status"],
                        name="finance_adj_student_ea181a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fee amount for this plan",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True, help_text="Whether this fee is mandatory"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("one_time", "One-time"), ("per_term", "Per term")],
                        default="one_time",
                        max_length=16,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        blank=True, help_text="Optional effective start date", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Program the plan applies to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_plans",
                        to="academics.program",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        help_text="Term/academic period the plan applies to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_plans",
                        to="academics.academicperiod",
                    ),
                ),
                (
                    "fee_type",
                    models.ForeignKey(
                        help_text="Fee type covered by this plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_plans",
                        to="finance.feetype",
                    ),
                ),
            ],
            options={
                "ordering": ["program", "term", "fee_type"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("program", "term", "fee_type"),
                        name="uniq_active_feeplan",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["student", "term"], name="finance_vou_student_cf277a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(fields=["status"], name="finance_vou_status_927025_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["student", "term"], name="finance_pay_student_c464aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="finance_pay_status_cb601d_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["student", "term"], name="finance_led_student_0dbde9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="finance_led_referen_8b5bdf_idx",
            ),
        ),
    ]
