# Generated by Django 5.1.4 on 2025-12-30 13:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('title_template', models.CharField(help_text='Title template (supports placeholders like {academic_period}, {batch})', max_length=255)),
                ('default_amount', models.DecimalField(decimal_places=2, help_text='Default charge amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('frequency_unit', models.CharField(choices=[('BLOCK', 'Block'), ('MONTH', 'Month'), ('TERM', 'Term'), ('YEAR', 'Year')], help_text='Frequency unit for charge generation', max_length=16)),
                ('frequency_interval', models.IntegerField(default=1, help_text='Frequency interval (e.g., every 2 blocks)', validators=[django.core.validators.MinValueValidator(1)])),
                ('auto_generate_mode', models.CharField(choices=[('MANUAL_WITH_REMINDER', 'Manual with Reminder'), ('GENERATE_ALL_NOW', 'Generate All Now'), ('REMIND_THEN_GENERATE', 'Remind Then Generate')], default='MANUAL_WITH_REMINDER', help_text='How charges should be generated', max_length=32)),
            ],
            options={
                'ordering': ['title_template'],
            },
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('challan_no', models.CharField(help_text='Unique challan number', max_length=64, unique=True)),
                ('amount_total', models.DecimalField(decimal_places=2, help_text='Total amount in this challan', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Challan status', max_length=16)),
                ('student', models.ForeignKey(help_text='Student this challan is for', on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('title', models.CharField(help_text='Charge title', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Charge amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField(help_text='Due date for this charge')),
                ('academic_period', models.ForeignKey(blank=True, help_text='Academic period this charge is for (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='academics.academicperiod')),
                ('template', models.ForeignKey(blank=True, help_text='Template used to generate this charge (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='finance.chargetemplate')),
            ],
            options={
                'ordering': ['-due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('received', models.BooleanField(default=True, help_text='Whether payment was received')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When payment was received')),
                ('amount_received', models.DecimalField(decimal_places=2, help_text='Amount received', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, help_text='Payment remarks/notes')),
                ('challan', models.ForeignKey(help_text='Challan this payment is for', on_delete=django.db.models.deletion.PROTECT, related_name='payment_logs', to='finance.challan')),
                ('received_by', models.ForeignKey(help_text='User who logged this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLedgerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of this ledger item', max_length=16)),
                ('charge', models.ForeignKey(help_text='Charge this ledger item is for', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_items', to='finance.charge')),
                ('student', models.ForeignKey(help_text='Student this ledger item is for', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_items', to='students.student')),
            ],
            options={
                'ordering': ['student', '-charge__due_date'],
            },
        ),
        migrations.AddField(
            model_name='challan',
            name='ledger_item',
            field=models.ForeignKey(help_text='Ledger item this challan is for', on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='finance.studentledgeritem'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['due_date'], name='finance_cha_due_dat_a37797_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['academic_period'], name='finance_cha_academi_3909bd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['challan'], name='finance_pay_challan_859f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['received_at'], name='finance_pay_receive_384795_idx'),
        ),
        migrations.AddIndex(
            model_name='studentledgeritem',
            index=models.Index(fields=['student', 'status'], name='finance_stu_student_90bc29_idx'),
        ),
        migrations.AddIndex(
            model_name='studentledgeritem',
            index=models.Index(fields=['charge', 'status'], name='finance_stu_charge__107223_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentledgeritem',
            unique_together={('student', 'charge')},
        ),
        migrations.AddIndex(
            model_name='challan',
            index=models.Index(fields=['challan_no'], name='finance_cha_challan_5e3721_idx'),
        ),
        migrations.AddIndex(
            model_name='challan',
            index=models.Index(fields=['student', 'status'], name='finance_cha_student_5f73ab_idx'),
        ),
    ]
