# Generated by Django 5.1.4 on 2025-10-21 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0002_alter_enrollment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="term",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
