# Generated by Django 5.1.4 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("notifications", "0001_initial")]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            old_name="notificatio_status_5cc05d_idx",
            new_name="notificatio_status_d92267_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            old_name="notificatio_category_124229_idx",
            new_name="notificatio_categor_fd561f_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            old_name="notificatio_created_4cbedc_idx",
            new_name="notificatio_created_274d42_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationaudience",
            old_name="notificatio_audience_9a9a0c_idx",
            new_name="notificatio_audienc_e78810_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationdeliverylog",
            old_name="notificatio_channel_315efa_idx",
            new_name="notificatio_channel_b87356_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationdeliverylog",
            old_name="notificatio_notific_6d24ae_idx",
            new_name="notificatio_notific_693fa4_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationinbox",
            old_name="notificatio_user_rea_0e078d_idx",
            new_name="notificatio_user_id_4561a6_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationinbox",
            old_name="notificatio_user_is__b33e7f_idx",
            new_name="notificatio_user_id_c8badc_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="The timestamp when the record was created."),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="The timestamp when the record was last updated."),
        ),
        migrations.AlterField(
            model_name="notificationaudience",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="The timestamp when the record was created."),
        ),
        migrations.AlterField(
            model_name="notificationaudience",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="The timestamp when the record was last updated."),
        ),
        migrations.AlterField(
            model_name="notificationdeliverylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="The timestamp when the record was created."),
        ),
        migrations.AlterField(
            model_name="notificationdeliverylog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="The timestamp when the record was last updated."),
        ),
        migrations.AlterField(
            model_name="notificationinbox",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="The timestamp when the record was created."),
        ),
        migrations.AlterField(
            model_name="notificationinbox",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="The timestamp when the record was last updated."),
        ),
    ]
