import { test, expect } from '@playwright/test'

test('staff import, mandatory password change, resumable profile, document review and reset', async ({ page, browser, request }, testInfo) => {
  const api = 'http://127.0.0.1:8021'
  const login = await request.post(`${api}/api/auth/login/`, { data: { identifier: 'browser-admin', password: 'Browser-Admin-9482!' } })
  expect(login.ok()).toBeTruthy()
  const admin = await login.json()
  const headers = { Authorization: `Bearer ${admin.tokens.access}` }
  const create = async (path: string, data: object) => {
    const response = await request.post(`${api}${path}`, { headers, data })
    expect(response.ok(), await response.text()).toBeTruthy()
    return response.json()
  }
  const program = await create('/api/academics/programs/', { name: 'Browser MBBS', structure_type: 'YEARLY' })
  const batch = await create('/api/academics/batches/', { program: program.id, name: 'Browser 2026', start_year: 2026 })
  const definition = await create('/api/compliance/definitions/', { title: 'Identity proof', requirement_type: 'document', is_active: true, is_onboarding_required: true })
  await page.goto('/login')
  await page.getByLabel(/email or username/i).fill('browser-admin')
  await page.getByLabel(/^password$/i).fill('Browser-Admin-9482!')
  await page.getByRole('button', { name: /sign in/i }).click()
  await expect(page).toHaveURL(/dashboard/)
  await page.goto('/compliance')
  await page.getByRole('tab', { name: 'Onboarding rules' }).click()
  await page.getByLabel('Document requirement').selectOption(String(definition.id))
  await page.getByRole('button', { name: 'Add rule' }).click()
  await expect(page.getByRole('button', { name: 'Archive', exact: true })).toBeVisible()
  await page.goto('/system/students/import')
  const csv = `first_name,last_name,registration_number,program_id,batch_id,initial_password\nAmina,Khan,BROWSER-001,${program.id},${batch.id},Temporary-9482!\nBad,Row,BROWSER-002,${program.id},999999,Temporary-9482!\n`
  await page.locator('input[type=file]').setInputFiles({ name: 'students.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await page.getByRole('button', { name: 'Preview Import', exact: true }).click()
  await expect(page.getByText('Student Import Preview', { exact: true })).toBeVisible()
  await expect(page.locator('body')).not.toContainText('Temporary-9482!')
  await page.getByRole('button', { name: 'Commit Import', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Commit import', exact: true }).click()
  await expect(page.getByText(/Created: 1, Unchanged: 0, Failed: 1/)).toBeVisible()
  await page.getByRole('button', { name: 'Details', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('COMMITTED')

  const context = await browser.newContext()
  const studentPage = await context.newPage()
  await studentPage.goto('http://127.0.0.1:5189/login')
  await studentPage.getByLabel(/email or username/i).fill('BROWSER-001')
  await studentPage.getByLabel(/^password$/i).fill('Temporary-9482!')
  await studentPage.getByRole('button', { name: /sign in/i }).click()
  await expect(studentPage).toHaveURL(/change-password-required/)
  await studentPage.getByLabel('Temporary password').fill('Temporary-9482!')
  await studentPage.getByLabel(/^New password/).fill('Student-Secure-7391!')
  await studentPage.getByLabel('Confirm new password').fill('Student-Secure-7391!')
  await studentPage.getByRole('button', { name: 'Change password', exact: true }).click()
  await expect(studentPage).toHaveURL(/student\/onboarding/)
  await studentPage.getByLabel('Email', { exact: true }).fill('amina@example.edu')
  await studentPage.getByLabel('Mobile number').fill('+923001234567')
  await studentPage.getByRole('button', { name: 'Save contact information' }).click()
  await expect(studentPage.getByText('Profile progress saved')).toBeVisible()
  await studentPage.reload()
  await expect(studentPage.getByLabel('Email', { exact: true })).toHaveValue('amina@example.edu')
  await studentPage.locator('input[type=file]').setInputFiles({ name: 'identity.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%%EOF') })
  await studentPage.getByRole('button', { name: 'Submit document' }).click()
  await expect(studentPage.getByRole('button', { name: 'Replace document' })).toBeVisible()
  await expect(studentPage.getByRole('button', { name: 'Download', exact: true })).toBeVisible()
  await page.goto('/compliance')
  await page.getByRole('button', { name: 'Submissions (1)' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: /Download file submitted/ }).click()
  expect((await download).suggestedFilename()).toBe('identity.pdf')
  await page.getByRole('button', { name: 'Reject Identity proof', exact: true }).click()
  await page.getByLabel('Notes for the student').fill('Please upload a clearer copy')
  await page.getByRole('dialog').getByRole('button', { name: 'Reject', exact: true }).click()
  await expect(page.getByText('Requirement rejected', { exact: true })).toBeVisible()
  await studentPage.reload()
  await expect(studentPage.getByText('Please upload a clearer copy')).toBeVisible()
  await studentPage.locator('input[type=file]').setInputFiles({ name: 'clear-identity.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%%EOF') })
  await studentPage.getByRole('button', { name: 'Replace document' }).click()
  await expect(studentPage.getByRole('button', { name: 'Download', exact: true })).toHaveCount(2)
  await page.reload()
  await page.getByRole('button', { name: 'Verify Identity proof', exact: true }).click()
  await page.getByLabel('Notes for the student').fill('Identity checked')
  await page.getByRole('dialog').getByRole('button', { name: 'Verify', exact: true }).click()
  await expect(page.getByText('Requirement verified', { exact: true })).toBeVisible()
  await studentPage.reload()
  await expect(studentPage.getByRole('button', { name: 'Replace document' })).toHaveCount(0)
  await studentPage.getByLabel('Date of birth').fill('2002-01-01')
  await studentPage.getByRole('button', { name: 'Select gender', exact: true }).click()
  await studentPage.getByRole('button', { name: 'Female', exact: true }).click()
  const saveSection = async (name: string) => {
    const [response] = await Promise.all([
      studentPage.waitForResponse((response) => response.url().includes('/me/onboarding/profile/') && response.request().method() === 'PATCH'),
      studentPage.getByRole('button', { name, exact: true }).click(),
    ])
    expect(response.ok(), await response.text()).toBeTruthy()
  }
  await saveSection('Save personal identity')
  await studentPage.getByLabel('Street', { exact: true }).fill('1 College Road')
  await studentPage.getByLabel('City', { exact: true }).fill('Lahore')
  await studentPage.getByLabel('Country', { exact: true }).fill('Pakistan')
  await saveSection('Save address')
  await studentPage.getByLabel('Name', { exact: true }).fill('Guardian Khan')
  await studentPage.getByLabel('Phone', { exact: true }).fill('+923001234568')
  await saveSection('Save emergency contact')
  await expect(studentPage.getByText('Required profile fields complete')).toBeVisible()
  await studentPage.screenshot({ path: testInfo.outputPath('completed-onboarding.png'), fullPage: true })
  await studentPage.goto('http://127.0.0.1:5189/dashboard/student')
  await expect(studentPage.getByRole('link', { name: 'Continue profile', exact: true })).toHaveCount(0)
  const studentsResponse = await request.get(`${api}/api/students/?search=BROWSER-001`, { headers })
  const student = (await studentsResponse.json()).results[0]
  await page.goto(`/students/${student.id}`)
  await expect(page.getByText('Onboarding', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Change placement', exact: true }).click()
  await page.getByRole('button', { name: 'Save placement', exact: true }).click()
  await expect(page.getByText('Placement updated')).toBeVisible()
  await page.getByRole('button', { name: 'Correct profile', exact: true }).click()
  await page.getByRole('dialog').getByLabel('Middle name').fill('Noor')
  await page.getByRole('dialog').getByLabel('Emergency contact name').fill('Guardian Khan')
  await page.getByRole('button', { name: 'Save correction' }).click()
  await expect(page.getByText('Student profile corrected')).toBeVisible()
  await studentPage.goto('http://127.0.0.1:5189/student/onboarding')
  await expect(studentPage.getByLabel('Middle name')).toHaveValue('Noor')
  await page.getByRole('button', { name: 'Reset password', exact: true }).click()
  await page.getByLabel('Temporary password', { exact: true }).fill('Reset-Secure-7391!')
  await page.getByLabel('Confirm temporary password').fill('Reset-Secure-7391!')
  await page.getByRole('button', { name: 'Set temporary password' }).click()
  await expect(page.getByText('Temporary password set')).toBeVisible()
  const oldToken = await studentPage.evaluate(() => localStorage.getItem('access_token'))
  const stale = await request.get(`${api}/api/students/me/`, { headers: { Authorization: `Bearer ${oldToken}` } })
  expect(stale.status()).toBe(401)
  const resetLogin = await request.post(`${api}/api/auth/login/`, { data: { identifier: 'BROWSER-001', password: 'Reset-Secure-7391!' } })
  expect(resetLogin.ok()).toBeTruthy()
  expect((await resetLogin.json()).user.password_change_required).toBe(true)
  const preserved = await request.get(`${api}/api/students/${student.id}/onboarding/`, { headers })
  const finalState = (await preserved.json()).onboarding
  expect(finalState.profile_status).toBe('complete')
  expect(finalState.documents_status).toBe('complete')
  expect(finalState.password_change_required).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('admin-onboarding-status.png'), fullPage: true })
  await context.close()
})
