# Generated by Django 5.1.4 on 2025-12-30 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('starts_at', models.DateTimeField(help_text='Session start time')),
                ('ends_at', models.DateTimeField(help_text='Session end time')),
                ('academic_period', models.ForeignKey(help_text='Academic period this session belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.academicperiod')),
                ('department', models.ForeignKey(help_text='Department this session is for (required)', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.department')),
                ('faculty', models.ForeignKey(help_text='Faculty user assigned to this session', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group this session is for', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.group')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['academic_period', 'group'], name='timetable_s_academi_013887_idx'), models.Index(fields=['faculty'], name='timetable_s_faculty_a5b647_idx'), models.Index(fields=['starts_at'], name='timetable_s_starts__86be5c_idx')],
            },
        ),
    ]
