# Generated by Django 5.1.4 on 2026-09-10 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_batch_start_year'),
        ('timetable', '0004_rename_timetable_t_weekly__jkl012_idx_timetable_t_weekly__fda2b3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')], help_text='Day of the week (0=Monday, 5=Saturday)')),
                ('start_time', models.TimeField(help_text='Entry start time')),
                ('end_time', models.TimeField(help_text='Entry end time')),
                ('room', models.CharField(blank=True, help_text='Room/venue (free text; no Room resource yet)', max_length=100)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_timetable_entries', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Group this entry is scoped to; blank means it applies to the whole batch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.group')),
                ('section', models.ForeignKey(help_text='Section (course + faculty context) taught in this slot', on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.section')),
                ('weekly_timetable', models.ForeignKey(help_text='Weekly timetable this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.weeklytimetable')),
            ],
            options={
                'verbose_name_plural': 'timetable entries',
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['weekly_timetable', 'day_of_week'], name='timetable_t_weekly__f222f1_idx'), models.Index(fields=['group'], name='timetable_t_group_i_947ccd_idx'), models.Index(fields=['status'], name='timetable_t_status_6e1d48_idx')],
            },
        ),
    ]
