# Generated by Django 5.1.4 on 2026-09-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_backfill_cells_to_entries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimetableCell',
        ),
    ]
