# Generated by Django 5.1.4 on 2025-12-30 13:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('LEAVE', 'Leave')], default='PRESENT', help_text='Attendance status', max_length=16)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this attendance was marked')),
                ('marked_by', models.ForeignKey(help_text='User who marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Session this attendance is for', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='timetable.session')),
                ('student', models.ForeignKey(help_text='Student this attendance is for', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'ordering': ['-marked_at'],
                'indexes': [models.Index(fields=['session', 'student'], name='attendance__session_33d78b_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx')],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
