# Generated by Django 5.1.4 on 2026-01-02 16:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("students", "0003_importjob"),
        ("timetable", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceInputJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="Target attendance date",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[("CSV", "CSV Upload"), ("SHEET", "Scanned Sheet")],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("COMMITTED", "Committed")],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_fingerprint", models.CharField(blank=True, max_length=64)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session this upload is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_input_jobs",
                        to="timetable.session",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["input_type"], name="attendance__input_t_870f48_idx"
                    ),
                    models.Index(
                        fields=["status"], name="attendance__status_d98ec3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BiometricPunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                ("punched_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("raw_identifier", models.CharField(blank=True, max_length=255)),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punches",
                        to="attendance.biometricdevice",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_punches",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-punched_at"],
                "indexes": [
                    models.Index(
                        fields=["punched_at"], name="attendance__punched_a40591_idx"
                    ),
                    models.Index(
                        fields=["student"], name="attendance__student_4f7353_idx"
                    ),
                ],
            },
        ),
    ]
