# Generated by Django 5.1.4 on 2025-12-30 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='request_data',
            field=models.JSONField(blank=True, help_text='Request data (JSON)', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='method',
            field=models.CharField(help_text='HTTP method (POST, PUT, PATCH, DELETE)', max_length=16),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model',
            field=models.CharField(blank=True, help_text='Model name (if applicable)', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, help_text='Object ID (if applicable)', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='path',
            field=models.TextField(help_text='Request path'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status_code',
            field=models.PositiveIntegerField(help_text='HTTP status code'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='summary',
            field=models.TextField(help_text='Action summary'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'timestamp'], name='audit_audit_actor_i_6355cc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model', 'object_id'], name='audit_audit_model_6c2be1_idx'),
        ),
    ]
