# Generated by Django 5.1.4 on 2026-01-26 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_add_missing_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_model_6c2be1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_entity_8edb54_idx',
            old_name='audit_audit_entity_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_86e815_idx',
            old_name='audit_audit_action_789abc_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='impersonated_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who initiated impersonation (if action was performed via impersonation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model',
            field=models.CharField(blank=True, help_text='Model name (deprecated, use entity instead)', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, help_text='Object ID (deprecated, use entity_id instead)', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_data',
            field=models.JSONField(blank=True, help_text='Request data (deprecated, use metadata instead)', null=True),
        ),
    ]
