# Generated by Django 5.1.4 on 2025-10-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0003_add_timestamp_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
