# Generated by Django 5.1.4 on 2025-12-31 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("admissions", "0006_add_application_draft"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create indexes if they don't exist (for fresh databases, skip rename)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions_a_email_8a3b2d_idx') THEN
                    ALTER INDEX admissions_a_email_8a3b2d_idx RENAME TO admissions__email_ad3c8c_idx;
                ELSE
                    CREATE INDEX IF NOT EXISTS admissions__email_ad3c8c_idx ON admissions_applicationdraft(email, status);
                END IF;
            END $$;
            """,
            reverse_sql="ALTER INDEX IF EXISTS admissions__email_ad3c8c_idx RENAME TO admissions_a_email_8a3b2d_idx;",
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions_a_status_9c4e5f_idx') THEN
                    ALTER INDEX admissions_a_status_9c4e5f_idx RENAME TO admissions__status_292cc2_idx;
                ELSE
                    CREATE INDEX IF NOT EXISTS admissions__status_292cc2_idx ON admissions_applicationdraft(status);
                END IF;
            END $$;
            """,
            reverse_sql="ALTER INDEX IF EXISTS admissions__status_292cc2_idx RENAME TO admissions_a_status_9c4e5f_idx;",
        ),
        migrations.AddField(
            model_name="student",
            name="batch_year",
            field=models.PositiveSmallIntegerField(
                default=2029,
                help_text="Graduating year (batch year). For example, for MBBS 5-year program, if admitted in 2024, batch_year would be 2029",
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="current_year",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Current academic year in the program (1-10)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Student date of birth", null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Student email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Student phone number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="date_of_birth",
            field=models.DateField(default="2000-01-01", help_text="Date of birth"),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the application was reviewed", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who reviewed this application",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The timestamp when the record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(
                help_text="Full name of the student", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.ForeignKey(
                help_text="Program the student is enrolled in",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admission_students",
                to="academics.program",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="reg_no",
            field=models.CharField(
                help_text="Student registration number", max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("graduated", "Graduated"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                help_text="Current status of the student",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The timestamp when the record was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="address",
            field=models.TextField(blank=True, help_text="Full address (legacy field)"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="batch_year",
            field=models.PositiveSmallIntegerField(
                help_text="Expected graduating year (batch year)",
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The timestamp when the record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="documents",
            field=models.FileField(
                blank=True,
                help_text="Uploaded documents (legacy field)",
                null=True,
                upload_to="student_applications/documents/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="domicile",
            field=models.FileField(
                help_text="Domicile certificate",
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="email",
            field=models.EmailField(help_text="Email address", max_length=254),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="father_id_card",
            field=models.FileField(
                help_text="Father ID card",
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="guardian_id_card",
            field=models.FileField(
                blank=True,
                help_text="Guardian ID card (required if guardian is not father)",
                null=True,
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="hssc_certificate",
            field=models.FileField(
                help_text="HSSC/FSC certificate",
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="mdcat_result",
            field=models.FileField(
                help_text="MDCAT result/screenshot",
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Admin notes about the application"
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="phone",
            field=models.CharField(help_text="Phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="previous_institution",
            field=models.CharField(
                blank=True,
                help_text="Previous institution name (legacy field)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="previous_qualification",
            field=models.CharField(
                blank=True,
                help_text="Previous educational qualification (legacy field)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="ssc_certificate",
            field=models.FileField(
                help_text="SSC/Matric certificate",
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Application status",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The timestamp when the record was last updated.",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["program", "batch_year"], name="admissions__program_787757_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["status"], name="admissions__status_32fe57_idx"),
        ),
        migrations.AddIndex(
            model_name="studentapplication",
            index=models.Index(fields=["status"], name="admissions__status_e024df_idx"),
        ),
        migrations.AddIndex(
            model_name="studentapplication",
            index=models.Index(
                fields=["program", "batch_year"], name="admissions__program_adb184_idx"
            ),
        ),
    ]
