# Generated by Django 5.1.4 on 2025-12-31 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("admissions", "0006_add_application_draft"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create indexes if they don't exist (for fresh databases, skip rename)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions_a_email_8a3b2d_idx') THEN
                    ALTER INDEX admissions_a_email_8a3b2d_idx RENAME TO admissions__email_ad3c8c_idx;
                ELSE
                    CREATE INDEX IF NOT EXISTS admissions__email_ad3c8c_idx ON admissions_applicationdraft(email, status);
                END IF;
            END $$;
            """,
            reverse_sql="ALTER INDEX IF EXISTS admissions__email_ad3c8c_idx RENAME TO admissions_a_email_8a3b2d_idx;",
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions_a_status_9c4e5f_idx') THEN
                    ALTER INDEX admissions_a_status_9c4e5f_idx RENAME TO admissions__status_292cc2_idx;
                ELSE
                    CREATE INDEX IF NOT EXISTS admissions__status_292cc2_idx ON admissions_applicationdraft(status);
                END IF;
            END $$;
            """,
            reverse_sql="ALTER INDEX IF EXISTS admissions__status_292cc2_idx RENAME TO admissions_a_status_9c4e5f_idx;",
        ),
        # Add batch_year field only if it doesn't exist (handles case where 0007_add_student_fields already added it)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='admissions_student' AND column_name='batch_year') THEN
                    ALTER TABLE admissions_student 
                    ADD COLUMN batch_year SMALLINT NOT NULL DEFAULT 2029
                    CHECK (batch_year >= 2000 AND batch_year <= 2100);
                    COMMENT ON COLUMN admissions_student.batch_year IS 'Graduating year (batch year). For example, for MBBS 5-year program, if admitted in 2024, batch_year would be 2029';
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE admissions_student DROP COLUMN IF EXISTS batch_year;",
        ),
        # Add current_year field only if it doesn't exist (handles case where 0007_add_student_fields already added it)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='admissions_student' AND column_name='current_year') THEN
                    ALTER TABLE admissions_student 
                    ADD COLUMN current_year SMALLINT NOT NULL DEFAULT 1
                    CHECK (current_year >= 1 AND current_year <= 10);
                    COMMENT ON COLUMN admissions_student.current_year IS 'Current academic year in the program (1-10)';
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE admissions_student DROP COLUMN IF EXISTS current_year;",
        ),
        # Add fields only if they don't exist (handles case where 0007_add_student_fields already added them)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='admissions_student' AND column_name='date_of_birth') THEN
                    ALTER TABLE admissions_student 
                    ADD COLUMN date_of_birth DATE NULL;
                    COMMENT ON COLUMN admissions_student.date_of_birth IS 'Student date of birth';
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='admissions_student' AND column_name='email') THEN
                    ALTER TABLE admissions_student 
                    ADD COLUMN email VARCHAR(254) NOT NULL DEFAULT '';
                    COMMENT ON COLUMN admissions_student.email IS 'Student email address';
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='admissions_student' AND column_name='phone') THEN
                    ALTER TABLE admissions_student 
                    ADD COLUMN phone VARCHAR(20) NOT NULL DEFAULT '';
                    COMMENT ON COLUMN admissions_student.phone IS 'Student phone number';
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='admissions_studentapplication' AND column_name='date_of_birth') THEN
                    ALTER TABLE admissions_studentapplication 
                    ADD COLUMN date_of_birth DATE NOT NULL DEFAULT '2000-01-01';
                    COMMENT ON COLUMN admissions_studentapplication.date_of_birth IS 'Date of birth';
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='admissions_studentapplication' AND column_name='reviewed_at') THEN
                    ALTER TABLE admissions_studentapplication 
                    ADD COLUMN reviewed_at TIMESTAMP NULL;
                    COMMENT ON COLUMN admissions_studentapplication.reviewed_at IS 'When the application was reviewed';
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='admissions_studentapplication' AND column_name='reviewed_by_id') THEN
                    ALTER TABLE admissions_studentapplication 
                    ADD COLUMN reviewed_by_id INTEGER NULL REFERENCES auth_user(id) ON DELETE SET NULL;
                    COMMENT ON COLUMN admissions_studentapplication.reviewed_by_id IS 'Admin user who reviewed this application';
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE admissions_student DROP COLUMN IF EXISTS date_of_birth;
            ALTER TABLE admissions_student DROP COLUMN IF EXISTS email;
            ALTER TABLE admissions_student DROP COLUMN IF EXISTS phone;
            ALTER TABLE admissions_studentapplication DROP COLUMN IF EXISTS date_of_birth;
            ALTER TABLE admissions_studentapplication DROP COLUMN IF EXISTS reviewed_at;
            ALTER TABLE admissions_studentapplication DROP COLUMN IF EXISTS reviewed_by_id;
            """,
        ),
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The timestamp when the record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(
                help_text="Full name of the student", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.ForeignKey(
                help_text="Program the student is enrolled in",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admission_students",
                to="academics.program",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="reg_no",
            field=models.CharField(
                help_text="Student registration number", max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("graduated", "Graduated"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                help_text="Current status of the student",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The timestamp when the record was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="address",
            field=models.TextField(blank=True, help_text="Full address (legacy field)"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="batch_year",
            field=models.PositiveSmallIntegerField(
                help_text="Expected graduating year (batch year)",
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The timestamp when the record was created.",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="documents",
            field=models.FileField(
                blank=True,
                help_text="Uploaded documents (legacy field)",
                null=True,
                upload_to="student_applications/documents/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="domicile",
            field=models.FileField(
                help_text="Domicile certificate",
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="email",
            field=models.EmailField(help_text="Email address", max_length=254),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="father_id_card",
            field=models.FileField(
                help_text="Father ID card",
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="guardian_id_card",
            field=models.FileField(
                blank=True,
                help_text="Guardian ID card (required if guardian is not father)",
                null=True,
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="hssc_certificate",
            field=models.FileField(
                help_text="HSSC/FSC certificate",
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="mdcat_result",
            field=models.FileField(
                help_text="MDCAT result/screenshot",
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Admin notes about the application"
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="phone",
            field=models.CharField(help_text="Phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="previous_institution",
            field=models.CharField(
                blank=True,
                help_text="Previous institution name (legacy field)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="previous_qualification",
            field=models.CharField(
                blank=True,
                help_text="Previous educational qualification (legacy field)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="ssc_certificate",
            field=models.FileField(
                help_text="SSC/Matric certificate",
                upload_to="student_applications/documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Application status",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The timestamp when the record was last updated.",
            ),
        ),
        # Add indexes only if they don't exist (handles case where 0007_add_student_fields already created them)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions__program_787757_idx') THEN
                    CREATE INDEX admissions__program_787757_idx ON admissions_student(program_id, batch_year);
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions__status_32fe57_idx') THEN
                    CREATE INDEX admissions__status_32fe57_idx ON admissions_student(status);
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions__status_e024df_idx') THEN
                    CREATE INDEX admissions__status_e024df_idx ON admissions_studentapplication(status);
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions__program_adb184_idx') THEN
                    CREATE INDEX admissions__program_adb184_idx ON admissions_studentapplication(program_id, batch_year);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS admissions__program_787757_idx;
            DROP INDEX IF EXISTS admissions__status_32fe57_idx;
            DROP INDEX IF EXISTS admissions__status_e024df_idx;
            DROP INDEX IF EXISTS admissions__program_adb184_idx;
            """,
        ),
    ]
