# Generated by Django 5.1.4 on 2026-01-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_add_student_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='email',
            field=models.EmailField(help_text='Email address', max_length=254),
        ),
    ]
