# Generated by Django 5.1.4 on 2026-01-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_rename_admissions_a_email_8a3b2d_idx_admissions__email_ad3c8c_idx_and_more'),
        ('admissions', '0008_alter_studentapplication_email'),
    ]

    operations = [
    ]
