# Generated by Django 5.1.4 on 2026-01-01 08:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_merge_20260101_0806'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename indexes only if old name exists and new name doesn't
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions_a_email_ad3c8c_idx') 
                   AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions__email_ad3c8c_idx') THEN
                    ALTER INDEX admissions_a_email_ad3c8c_idx RENAME TO admissions__email_ad3c8c_idx;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions_a_status_292cc2_idx') 
                   AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions__status_292cc2_idx') THEN
                    ALTER INDEX admissions_a_status_292cc2_idx RENAME TO admissions__status_292cc2_idx;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions__email_ad3c8c_idx') THEN
                    ALTER INDEX admissions__email_ad3c8c_idx RENAME TO admissions_a_email_ad3c8c_idx;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'admissions__status_292cc2_idx') THEN
                    ALTER INDEX admissions__status_292cc2_idx RENAME TO admissions_a_status_292cc2_idx;
                END IF;
            END $$;
            """,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked user account (optional until account is created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch_year',
            field=models.PositiveSmallIntegerField(default=2029, help_text='Graduating year (batch year). For example, for an MBBS 5-year program, if admitted in 2024, batch_year would be 2029. The default value of 2029 is used for legacy data corresponding to this initial cohort and should normally be overridden by application logic when creating new students.', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
