# Generated by Django 5.1.4 on 2025-12-30 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('title', models.CharField(help_text='Exam title', max_length=255)),
                ('exam_type', models.CharField(blank=True, help_text="Type of exam (e.g., 'Midterm', 'Final', 'Quiz')", max_length=128)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Scheduled date and time for the exam', null=True)),
                ('published', models.BooleanField(default=False, help_text='Whether this exam is published')),
                ('version', models.IntegerField(default=1, help_text='Version number for audit trail')),
                ('passing_mode', models.CharField(choices=[('TOTAL_ONLY', 'Total Only'), ('COMPONENT_WISE', 'Component Wise'), ('HYBRID', 'Hybrid')], default='TOTAL_ONLY', help_text='Mode for determining pass/fail', max_length=32)),
                ('pass_total_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum total marks required to pass', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pass_total_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum total percentage required to pass', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fail_if_any_component_fail', models.BooleanField(default=False, help_text='If True, student fails if any mandatory component fails')),
                ('academic_period', models.ForeignKey(help_text='Academic period this exam belongs to (required)', on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.academicperiod')),
                ('department', models.ForeignKey(blank=True, help_text='Department for this exam (nullable for combined exams)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.department')),
            ],
            options={
                'ordering': ['-scheduled_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExamComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('name', models.CharField(help_text="Component name (e.g., 'Written', 'Practical', 'Viva')", max_length=255)),
                ('sequence', models.IntegerField(default=1, help_text='Order/sequence of this component')),
                ('max_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks for this component', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pass_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum marks required to pass this component', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pass_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum percentage required to pass this component', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_mandatory_to_pass', models.BooleanField(default=False, help_text='Whether this component must be passed for overall pass')),
                ('department', models.ForeignKey(blank=True, help_text='Department for this component (nullable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_components', to='academics.department')),
                ('exam', models.ForeignKey(help_text='Exam this component belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='exams.exam')),
            ],
            options={
                'ordering': ['exam', 'sequence', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_period'], name='exams_exam_academi_9f6295_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['department'], name='exams_exam_departm_de0fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['published'], name='exams_exam_publish_7f6de8_idx'),
        ),
        migrations.AddIndex(
            model_name='examcomponent',
            index=models.Index(fields=['exam', 'sequence'], name='exams_examc_exam_id_6c6dcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examcomponent',
            unique_together={('exam', 'sequence')},
        ),
    ]
