# Generated by Django 5.1.4 on 2025-12-31 18:55

import apps.intake.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0002_add_student_foreign_key"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studentintakesubmission",
            new_name="student_int_cnic_or_09bf9f_idx",
            old_name="student_int_cnic_or_12345_idx",
        ),
        migrations.RenameIndex(
            model_name="studentintakesubmission",
            new_name="student_int_mobile_8209c8_idx",
            old_name="student_int_mobile_12345_idx",
        ),
        migrations.RenameIndex(
            model_name="studentintakesubmission",
            new_name="student_int_email_68ab65_idx",
            old_name="student_int_email_12345_idx",
        ),
        migrations.RenameIndex(
            model_name="studentintakesubmission",
            new_name="student_int_mdcat_r_2ad5ff_idx",
            old_name="student_int_mdcat_r_12345_idx",
        ),
        migrations.RenameIndex(
            model_name="studentintakesubmission",
            new_name="student_int_status_655447_idx",
            old_name="student_int_status_12345_idx",
        ),
        migrations.RenameIndex(
            model_name="studentintakesubmission",
            new_name="student_int_submiss_fa0320_idx",
            old_name="student_int_submiss_12345_idx",
        ),
        migrations.AlterField(
            model_name="studentintakesubmission",
            name="cnic_back",
            field=models.FileField(
                blank=True,
                help_text="CNIC back (pdf/jpg/png, max 3MB)",
                null=True,
                upload_to=apps.intake.models.intake_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentintakesubmission",
            name="cnic_front",
            field=models.FileField(
                blank=True,
                help_text="CNIC front (pdf/jpg/png, max 3MB)",
                null=True,
                upload_to=apps.intake.models.intake_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentintakesubmission",
            name="domicile",
            field=models.FileField(
                blank=True,
                help_text="Domicile certificate (pdf/jpg/png, max 3MB)",
                null=True,
                upload_to=apps.intake.models.intake_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentintakesubmission",
            name="fsc_certificate",
            field=models.FileField(
                blank=True,
                help_text="FSc certificate (pdf/jpg/png, max 3MB)",
                null=True,
                upload_to=apps.intake.models.intake_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentintakesubmission",
            name="matric_certificate",
            field=models.FileField(
                blank=True,
                help_text="Matric certificate (pdf/jpg/png, max 3MB)",
                null=True,
                upload_to=apps.intake.models.intake_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentintakesubmission",
            name="migration_certificate",
            field=models.FileField(
                blank=True,
                help_text="Migration certificate (pdf/jpg/png, max 3MB)",
                null=True,
                upload_to=apps.intake.models.intake_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentintakesubmission",
            name="other_document_1",
            field=models.FileField(
                blank=True,
                help_text="Other document 1 (pdf/jpg/png, max 3MB)",
                null=True,
                upload_to=apps.intake.models.intake_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentintakesubmission",
            name="other_document_2",
            field=models.FileField(
                blank=True,
                help_text="Other document 2 (pdf/jpg/png, max 3MB)",
                null=True,
                upload_to=apps.intake.models.intake_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentintakesubmission",
            name="passport_size_photo",
            field=models.ImageField(
                help_text="Passport-size photograph (jpg/png only, max 1MB, REQUIRED)",
                upload_to=apps.intake.models.intake_upload_path,
            ),
        ),
    ]
