# Generated by Django 5.1.4 on 2026-01-02 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the record was last updated.",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when import was completed or failed",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PREVIEWED", "Previewed"),
                            ("COMMITTED", "Committed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Current status of the import job",
                        max_length=32,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("CREATE_ONLY", "Create Only"), ("UPSERT", "Upsert")],
                        default="CREATE_ONLY",
                        help_text="Import mode: create-only or upsert",
                        max_length=32,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename of the uploaded CSV",
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded CSV file",
                        upload_to="imports/students/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA256 hash of the file for duplicate detection",
                        max_length=64,
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of rows in the CSV (excluding header)",
                    ),
                ),
                (
                    "valid_rows",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of valid rows that passed validation",
                    ),
                ),
                (
                    "invalid_rows",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of invalid rows with errors"
                    ),
                ),
                (
                    "created_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of students created during commit"
                    ),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of students updated during commit (upsert mode)",
                    ),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of rows that failed during commit"
                    ),
                ),
                (
                    "error_report_file",
                    models.FileField(
                        blank=True,
                        help_text="CSV file containing invalid rows with error messages",
                        null=True,
                        upload_to="imports/students/errors/%Y/%m/%d/",
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        help_text="Structured summary of import results",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who initiated the import",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="students_im_status_a8c7d9_idx",
                    ),
                    models.Index(
                        fields=["file_hash", "mode"],
                        name="students_im_file_ha_c584d0_idx",
                    ),
                    models.Index(
                        fields=["created_by"], name="students_im_created_a24243_idx"
                    ),
                ],
            },
        ),
    ]
