# Generated by Django 5.1.4 on 2026-01-26 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('code', models.CharField(help_text="Unique task code (e.g., 'students.view', 'enrollment.create')", max_length=200, unique=True)),
                ('name', models.CharField(help_text='Human-readable task name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this permission task allows')),
                ('module', models.CharField(help_text="Module this task belongs to (e.g., 'students', 'enrollment')", max_length=100)),
            ],
            options={
                'ordering': ['module', 'code'],
                'indexes': [models.Index(fields=['module'], name='core_permis_module_5f5cac_idx'), models.Index(fields=['code'], name='core_permis_code_081883_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('name', models.CharField(help_text='Role name (e.g., Admin, Student, Faculty)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of the role's purpose and responsibilities")),
                ('is_system_role', models.BooleanField(default=False, help_text='True for built-in system roles that cannot be deleted')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_role_name_9798dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('role', models.ForeignKey(help_text='Role being assigned tasks', on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='core.role')),
                ('task', models.ForeignKey(help_text='Permission task being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.permissiontask')),
            ],
            options={
                'indexes': [models.Index(fields=['role', 'task'], name='core_roleta_role_id_9e5cf7_idx')],
                'unique_together': {('role', 'task')},
            },
        ),
        migrations.CreateModel(
            name='UserTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when the record was last updated.')),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who granted this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_task_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Permission task being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core.permissiontask')),
                ('user', models.ForeignKey(help_text='User being assigned a task', on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'task'], name='core_userta_user_id_4ed605_idx')],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
